"""Deterministic Anki package export for validated flashcards."""

from __future__ import annotations

import json
import hashlib
import sqlite3
import tempfile
import zipfile
from pathlib import Path

from .models import Card


def export_apkg(cards: list[Card] | tuple[Card, ...], deck_name: str = "Document deck") -> bytes:
    fingerprint = json.dumps([(card.front, card.back, card.type) for card in cards], ensure_ascii=False, separators=(",", ":")) + deck_name
    now = int(hashlib.sha256(fingerprint.encode()).hexdigest()[:12], 16)
    with tempfile.TemporaryDirectory() as directory:
        collection = Path(directory) / "collection.anki2"
        con = sqlite3.connect(collection)
        con.executescript("""CREATE TABLE col (id integer primary key, crt integer not null, mod integer not null, scm integer not null, ver integer not null, dty integer not null, usn integer not null, ls integer not null, conf text not null, models text not null, decks text not null, dconf text not null, tags text not null); CREATE TABLE notes (id integer primary key, guid text not null, mid integer not null, mod integer not null, usn integer not null, tags text not null, flds text not null, sfld integer not null, csum integer not null, flags integer not null, data text not null); CREATE TABLE cards (id integer primary key, nid integer not null, did integer not null, ord integer not null, mod integer not null, usn integer not null, type integer not null, queue integer not null, due integer not null, ivl integer not null, factor integer not null, reps integer not null, lapses integer not null, left integer not null, odue integer not null, odid integer not null, flags integer not null, data text not null);""")
        deck_id, model_id = now, now + 1
        model = {str(model_id): {"name": "Document Basic", "type": 0, "mod": now, "usn": -1, "sortf": 0, "did": deck_id, "tmpls": [{"name": "Card 1", "ord": 0, "qfmt": "{{Front}}", "afmt": "{{FrontSide}}<hr id=answer>{{Back}}"}], "flds": [{"name": "Front", "ord": 0}, {"name": "Back", "ord": 1}]}}
        decks = {str(deck_id): {"name": deck_name, "id": deck_id, "mod": now, "usn": -1, "desc": "Generated by document-engine"}}
        con.execute("INSERT INTO col VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", (1, now // 1000, now, 11, 0, 0, -1, 0, "{}", json.dumps(model), json.dumps(decks), "{}", ""))
        for index, card in enumerate(cards):
            note_id, card_id = now + index + 10, now + index + 1000
            guid = hashlib.sha1(f"{deck_name}:{index}:{card.front}:{card.back}".encode()).hexdigest()[:10]
            con.execute("INSERT INTO notes VALUES (?,?,?,?,?,?,?,?,?,?,?)", (note_id, guid, model_id, now, -1, "", card.front + "\x1f" + card.back, card.front, 0, 0, ""))
            con.execute("INSERT INTO cards VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", (card_id, note_id, deck_id, 0, now, -1, 0, 0, index + 1, 0, 0, 0, 0, 0, 0, 0, 0, ""))
        con.commit(); con.close()
        output = Path(directory) / "deck.apkg"
        with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
            archive.write(collection, "collection.anki2")
            archive.writestr("media", "{}")
        return output.read_bytes()
